//
//  TempNoteListPresenter.swift
//  Trainee app
//
//  Created by Stanislav Lezovsky on 01.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TempNoteListPresentationLogic
{
  func presentSomething(response: TempNoteList.Something.Response)
}

class TempNoteListPresenter: TempNoteListPresentationLogic
{
  weak var viewController: TempNoteListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: TempNoteList.Something.Response)
  {
    let viewModel = TempNoteList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
