//
//  TempNoteListRouter.swift
//  Trainee app
//
//  Created by Stanislav Lezovsky on 01.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TempNoteListRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol TempNoteListDataPassing
{
  var dataStore: TempNoteListDataStore? { get }
}

class TempNoteListRouter: NSObject, TempNoteListRoutingLogic, TempNoteListDataPassing
{
  weak var viewController: TempNoteListViewController?
  var dataStore: TempNoteListDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: TempNoteListViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: TempNoteListDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
