//
//  TempNoteListInteractor.swift
//  Trainee app
//
//  Created by Stanislav Lezovsky on 01.06.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TempNoteListBusinessLogic
{
  func doSomething(request: TempNoteList.Something.Request)
}

protocol TempNoteListDataStore
{
  //var name: String { get set }
}

class TempNoteListInteractor: TempNoteListBusinessLogic, TempNoteListDataStore
{
  var presenter: TempNoteListPresentationLogic?
  var worker: TempNoteListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: TempNoteList.Something.Request)
  {
    worker = TempNoteListWorker()
    worker?.doSomeWork()
    
    let response = TempNoteList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
